version: "3.9"

services:
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/code
      - ./backend/storage:/code/storage
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    working_dir: /code
    networks:
      - client-dashboard-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - client-dashboard-network
    restart: always

networks:
  client-dashboard-network:
    driver: bridge
